[package]
name = "meta"
version = "0.1.0"
authors = ["Marc Biegota <marc.biegota@5minds.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
